name: CI/CD Node.js Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Tests (Karma + Jasmine)
        run: npx karma start --single-run

      - name: Run ESLint
        run: npx eslint . --fix

      - name: Run Snyk (Security Scan)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: npx snyk test || echo "Snyk encontro vulnerabilidades, continuando flujo."

      - name: Run Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonar-scanner || echo "Snyk encontro vulnerabilidades, continuando flujo."
          sonar-scanner \
            -Dsonar.projectKey=decimas \
            -Dsonar.sources=./src \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${SONAR_TOKEN} \
            -Dsonar.branch.name=main

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push Docker image
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=organizaciontesting \
            -Dsonar.organization=OrganizacionTesting \
            -Dsonar.sources=./src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN} \
            -Dsonar.branch.name=main
